//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DegreeType
    {
        public int Id { get; set; }
        public Nullable<int> DegreeLevelId { get; set; }
        public string DegreeType1 { get; set; }
    }
}
