//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JobPortalContext : DbContext
    {
        public JobPortalContext()
            : base("name=JobPortalContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Academics> Academics { get; set; }
        public DbSet<AccountType> AccountType { get; set; }
        public DbSet<CareerLevel> CareerLevel { get; set; }
        public DbSet<City> City { get; set; }
        public DbSet<Country> Country { get; set; }
        public DbSet<DegreeLevel> DegreeLevel { get; set; }
        public DbSet<DegreeType> DegreeType { get; set; }
        public DbSet<Experience> Experience { get; set; }
        public DbSet<FunctionalArea> FunctionalArea { get; set; }
        public DbSet<JobRole> JobRole { get; set; }
        public DbSet<ProfessionalIndustry> ProfessionalIndustry { get; set; }
        public DbSet<Resume> Resume { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<WorkExperience> WorkExperience { get; set; }
    }
}
