//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobRole
    {
        public int Id { get; set; }
        public Nullable<int> FunctionalAreaId { get; set; }
        public string JobRole1 { get; set; }
    }
}
