//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public Nullable<int> ProfessionalIndustryId { get; set; }
        public Nullable<int> FunctionalAreaId { get; set; }
        public Nullable<int> CareerLevelId { get; set; }
        public Nullable<int> JobRoleId { get; set; }
        public string MobileNo { get; set; }
        public string ContactNo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public Nullable<int> AccountType { get; set; }
    }
}
